[package]
name = "tetrotime"
version = "0.1.0"
edition = "2021"

[dependencies]
pixel_loop = { git="https://github.com/jakobwesthoff/pixel_loop.git", branch = "main", default-features = false, features = [
  "crossterm",
] }
anyhow = "*"
chrono = "0.4.38"
